"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import "./workspace.css";

type User={email:string;name:string;role:string;unitId:string};
type Kpi={id:number;code:string;name:string;unit:string;target:number;actual:number;year:number;source:string};
type Outcome={id:number;programId:string;code:string;name:string;score:number;semester:string;target:number};
type Workflow={id:number;entity_type:string;entity_id:number;unit_id:string;year:number;title:string;stage:string;status:string;owner_email:string;reviewer_email?:string;approved_by?:string;finding?:string;recommendation?:string;corrective_action?:string;due_at?:number};
type Doc={id:number;title:string;type:string;unitId:string;year:number;visibility:string;url:string};
type Portal={kpis:Kpi[];outcomes:Outcome[];workflows:Workflow[];documents:Doc[];repositories:unknown[];laboratories:unknown[];lecturers:unknown[]};
type Tab="overview"|"kpi"|"obe"|"ppepp"|"evidence"|"documents"|"users";

const blank:Portal={kpis:[],outcomes:[],workflows:[],documents:[],repositories:[],laboratories:[],lecturers:[]};

export default function Workspace(){
  const [user,setUser]=useState<User|null>(null),[permissions,setPermissions]=useState<string[]>([]),[data,setData]=useState<Portal>(blank),[tab,setTab]=useState<Tab>("overview"),[message,setMessage]=useState("");
  const [login,setLogin]=useState({email:"",password:""});
  const can=(p:string)=>permissions.includes(p);
  const load=useCallback(async()=>{const me=await fetch("/api/me",{cache:"no-store"});const identity=await me.json();setUser(identity.user);setPermissions(identity.permissions??[]);if(identity.user?.email&&identity.permissions?.includes("workspace.read")){const res=await fetch("/api/portal",{cache:"no-store"});const json=await res.json();if(res.ok)setData(json);else setMessage(json.error)}else setData(blank)},[]);
  useEffect(()=>{void load()},[load]);
  async function signIn(e:React.FormEvent){e.preventDefault();setMessage("Memeriksa akun…");const r=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(login)});const j=await r.json();setMessage(r.ok?"Login berhasil.":j.error);if(r.ok){setLogin({email:"",password:""});await load()}}
  async function signOut(){await fetch("/api/auth/logout",{method:"POST"});setUser(null);setPermissions([]);setData(blank);setTab("overview")}
  const nav=useMemo(()=>[
    ["overview","Ikhtisar","workspace.read"],["kpi","Sasaran & KPI","workspace.read"],["obe","OBE & Kurikulum","obe.read"],["ppepp","SPMI / PPEPP","workspace.read"],["evidence","Input Evidence","workspace.read"],["documents","Dokumen","document.manage"],["users","Pengguna","user.manage"],
  ].filter(([, ,p])=>permissions.includes(String(p))) as string[][],[permissions]);

  if(!user?.email||!can("workspace.read"))return <div className="workspace-login"><a href="/" className="back-public">← Website Jurusan</a><section><img src="/api/logo" alt="Logo Polbeng"/><span>PORTAL INTERNAL</span><h1>Ruang kerja tata kelola Jurusan Kemaritiman</h1><p>Masuk menggunakan akun yang telah diberikan role dan unit kerja. Data KPI, OBE, evidence, evaluasi, dan tindak lanjut berada di ruang terproteksi.</p><form onSubmit={signIn}><label>Email<input type="email" required value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/></label><label>Password<input type="password" required value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/></label><button>Masuk ke workspace</button></form>{message&&<small>{message}</small>}</section></div>;

  return <div className="workspace-shell">
    <aside className="workspace-nav"><a className="ws-brand" href="/"><img src="/api/logo" alt=""/><span><b>Kemaritiman</b><small>Internal Workspace</small></span></a><div className="ws-user"><span>{user.name.slice(0,2).toUpperCase()}</span><div><b>{user.name}</b><small>{user.role} · {user.unitId}</small></div></div><nav>{nav.map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id as Tab)}>{label}</button>)}</nav><div className="ws-bottom"><a href="/">Website publik</a><button onClick={signOut}>Keluar</button></div></aside>
    <main className="workspace-main"><header><div><span>JURUSAN KEMARITIMAN · POLBENG</span><h1>{nav.find(x=>x[0]===tab)?.[1]}</h1></div><div className="role-chip">{user.role}<small>{user.unitId}</small></div></header><div className="ws-content">
      {message&&<div className="ws-message">{message}<button onClick={()=>setMessage("")}>×</button></div>}
      {tab==="overview"&&<Overview data={data} user={user}/>} 
      {tab==="kpi"&&<KpiPanel rows={data.kpis} editable={can("kpi.target.manage")} reload={load} setMessage={setMessage}/>} 
      {tab==="obe"&&<ObePanel rows={data.outcomes} user={user}/>} 
      {tab==="ppepp"&&<PpeppPanel rows={data.workflows} permissions={permissions} reload={load} setMessage={setMessage}/>} 
      {tab==="evidence"&&<EvidencePanel user={user} permissions={permissions} reload={load} setMessage={setMessage}/>} 
      {tab==="documents"&&<DocumentPanel user={user} docs={data.documents} reload={load} setMessage={setMessage}/>} 
      {tab==="users"&&<UsersPanel setMessage={setMessage}/>} 
    </div></main>
  </div>;
}

function Overview({data,user}:{data:Portal;user:User}){
  const achieved=data.kpis.filter(x=>Number(x.actual)>=Number(x.target)).length;
  const pending=data.workflows.filter(x=>!["APPROVED","CLOSED"].includes(x.status)).length;
  const evaluation=data.workflows.filter(x=>["SUBMITTED","REVIEWED","EVALUATED"].includes(x.status)).length;
  return <><section className="ws-hero"><div><span>WORKSPACE {user.role}</span><h2>Data kerja, evaluasi, dan keputusan mutu berada dalam satu alur yang dapat diaudit.</h2><p>Setiap evidence bergerak dari pelaksanaan menuju evaluasi, pengendalian, dan peningkatan sesuai kewenangan role.</p></div><div className="ws-cycle">{["P","P","E","P","P"].map((x,i)=><i key={i}>{x}</i>)}</div></section><div className="ws-metrics"><article><span>KPI aktif</span><b>{data.kpis.length}</b><small>{achieved} memenuhi target</small></article><article><span>Workflow terbuka</span><b>{pending}</b><small>butuh proses berikutnya</small></article><article><span>Antrian evaluasi</span><b>{evaluation}</b><small>evidence / temuan</small></article><article><span>Hasil OBE</span><b>{data.outcomes.length}</b><small>rekaman CPL</small></article></div><section className="ws-panel"><div className="ws-heading"><div><span>ALUR TERBARU</span><h3>Status PPEPP</h3></div></div><div className="workflow-mini">{data.workflows.slice(0,8).map(w=><div key={w.id}><b>{w.title}</b><span>{w.unit_id} · {w.stage}</span><em className={`status s-${w.status.toLowerCase()}`}>{w.status}</em></div>)}{!data.workflows.length&&<p className="ws-empty">Belum ada evidence yang diajukan.</p>}</div></section></>;
}

function KpiPanel({rows,editable,reload,setMessage}:{rows:Kpi[];editable:boolean;reload:()=>Promise<void>;setMessage:(s:string)=>void}){
  async function save(k:Kpi,target:number){const r=await fetch("/api/admin/kpis",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:k.id,target})});const j=await r.json();setMessage(r.ok?"Target KPI diperbarui.":j.error);if(r.ok)await reload()}
  return <section className="ws-panel"><div className="ws-heading"><div><span>SASARAN STRATEGIS</span><h3>KPI berbasis evidence yang telah disetujui</h3></div><small>Realisasi hanya dihitung dari evidence berstatus APPROVED/CLOSED. Target hanya dapat diubah role berwenang.</small></div><div className="kpi-table">{rows.map(k=><KpiRow key={k.id} k={k} editable={editable} save={save}/>)}</div></section>;
}
function KpiRow({k,editable,save}:{k:Kpi;editable:boolean;save:(k:Kpi,t:number)=>Promise<void>}){const [target,setTarget]=useState(Number(k.target));return <div className="kpi-line"><div><span>{k.code}</span><b>{k.name}</b><small>{k.source} · {k.year}</small></div><label>Target<input type="number" value={target} disabled={!editable} onChange={e=>setTarget(Number(e.target.value))}/></label><div><span>Realisasi</span><strong>{Number(k.actual).toFixed(1)}%</strong></div>{editable?<button onClick={()=>save(k,target)}>Simpan</button>:<em>Baca saja</em>}</div>}

function ObePanel({rows,user}:{rows:Outcome[];user:User}){
  const grouped=["NAUTIKA","KPN"].map(p=>({program:p,rows:rows.filter(x=>x.programId===p)})).filter(x=>user.role!=="KAPRODI"||x.program===user.unitId);
  return <>{grouped.map(g=><section className="ws-panel" key={g.program}><div className="ws-heading"><div><span>OUTCOME-BASED EDUCATION</span><h3>{g.program==="NAUTIKA"?"D3 Nautika":"D3 KPN"}</h3></div><small>Hasil detail dapat dibaca untuk review. Nilai baru menjadi realisasi KPI setelah evidence OBE disetujui pada PPEPP.</small></div><div className="obe-list">{g.rows.map(r=><div key={r.id}><span>{r.code}</span><div><b>{r.name}</b><div className="obe-bar"><i style={{width:`${Math.min(Number(r.score),100)}%`}}/></div><small>{r.semester}</small></div><strong>{Number(r.score).toFixed(1)}%</strong><em className={Number(r.score)>=Number(r.target)?"met":"gap"}>{Number(r.score)>=Number(r.target)?"Tercapai":"Gap"}</em></div>)}{!g.rows.length&&<p className="ws-empty">Belum ada hasil OBE pada unit ini.</p>}</div></section>)}</>;
}

function PpeppPanel({rows,permissions,reload,setMessage}:{rows:Workflow[];permissions:string[];reload:()=>Promise<void>;setMessage:(s:string)=>void}){
  async function move(w:Workflow,status:string){const finding=status==="EVALUATED"?window.prompt("Temuan evaluasi (opsional)")??undefined:undefined;const recommendation=status==="EVALUATED"?window.prompt("Rekomendasi (opsional)")??undefined:undefined;const correctiveAction=status==="FOLLOW_UP"?window.prompt("Rencana tindak lanjut")??undefined:undefined;const r=await fetch("/api/workspace/workflows",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:w.id,status,finding,recommendation,correctiveAction})});const j=await r.json();setMessage(r.ok?`Workflow menjadi ${status}.`:j.error);if(r.ok)await reload()}
  function actions(w:Workflow){const a:{label:string;status:string}[]=[];if(permissions.includes("evaluation.manage")&&w.status==="SUBMITTED")a.push({label:"Evaluasi",status:"EVALUATED"});if(permissions.includes("approval.manage")&&w.status==="EVALUATED")a.push({label:"Setujui",status:"APPROVED"});if(permissions.includes("corrective_action.manage")&&w.status==="APPROVED")a.push({label:"Tindak lanjut",status:"FOLLOW_UP"});if(permissions.includes("corrective_action.manage")&&["APPROVED","FOLLOW_UP"].includes(w.status))a.push({label:"Tutup",status:"CLOSED"});return a}
  return <section className="ws-panel"><div className="ws-heading"><div><span>SPMI · PPEPP</span><h3>Evidence, evaluasi, pengendalian, peningkatan</h3></div><small>GKM mengevaluasi, pimpinan melakukan approval/pengendalian, pemilik proses menindaklanjuti.</small></div><div className="workflow-list">{rows.map(w=><article key={w.id}><div><span>{w.entity_type} · {w.year}</span><h4>{w.title}</h4><p>{w.unit_id} · Pemilik: {w.owner_email}</p>{w.finding&&<p><b>Temuan:</b> {w.finding}</p>}{w.recommendation&&<p><b>Rekomendasi:</b> {w.recommendation}</p>}{w.corrective_action&&<p><b>Tindak lanjut:</b> {w.corrective_action}</p>}</div><div className="workflow-side"><em className={`status s-${w.status.toLowerCase()}`}>{w.status}</em><small>{w.stage}</small>{actions(w).map(a=><button key={a.status} onClick={()=>move(w,a.status)}>{a.label}</button>)}</div></article>)}{!rows.length&&<p className="ws-empty">Belum ada workflow PPEPP.</p>}</div></section>;
}

function EvidencePanel({user,permissions,reload,setMessage}:{user:User;permissions:string[];reload:()=>Promise<void>;setMessage:(s:string)=>void}){
  const program=permissions.includes("evidence.program.upload"),lab=permissions.includes("evidence.lab.upload");const options=[...(program?["OBE","TRACER","ACADEMIC"]:[]),...(lab?["LAB"]:[])];
  const [instrument,setInstrument]=useState(options[0]??""),[unit,setUnit]=useState(user.role==="KAPRODI"?user.unitId:"NAUTIKA"),[year,setYear]=useState(new Date().getFullYear()),[file,setFile]=useState<File|null>(null);
  async function submit(e:React.FormEvent){e.preventDefault();if(!file||!instrument)return;const f=new FormData();f.set("file",file);f.set("instrument",instrument);f.set("unitId",instrument==="LAB"?"LAB":unit);f.set("year",String(year));const r=await fetch("/api/admin/upload-evidence",{method:"POST",body:f});const j=await r.json();setMessage(r.ok?j.message:j.error);if(r.ok){setFile(null);await reload()}}
  if(!options.length)return <section className="ws-panel"><p className="ws-empty">Role ini berfungsi untuk review/evaluasi dan tidak memiliki permission input evidence.</p></section>;
  return <section className="ws-panel evidence-panel"><div className="ws-heading"><div><span>PELAKSANAAN</span><h3>Input evidence sumber KPI</h3></div><small>File asli, checksum, pengunggah, dan audit trail disimpan. Setelah upload, evidence berstatus SUBMITTED dan belum memengaruhi KPI sampai disetujui.</small></div><form onSubmit={submit}><label>Instrumen<select value={instrument} onChange={e=>setInstrument(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label>{instrument!=="LAB"&&<label>Program studi<select value={unit} disabled={user.role==="KAPRODI"} onChange={e=>setUnit(e.target.value)}><option value="NAUTIKA">D3 Nautika</option><option value="KPN">D3 KPN</option></select></label>}<label>Tahun<input type="number" value={year} onChange={e=>setYear(Number(e.target.value))}/></label><label>Excel<input type="file" accept=".xlsx,.xls" required onChange={e=>setFile(e.target.files?.[0]??null)}/></label><button>Unggah & ajukan evaluasi</button></form></section>;
}

function DocumentPanel({user,docs,reload,setMessage}:{user:User;docs:Doc[];reload:()=>Promise<void>;setMessage:(s:string)=>void}){
  const [form,setForm]=useState({title:"",type:"RENSTRA",unitId:user.role==="KAPRODI"?user.unitId:"UPPS",year:new Date().getFullYear(),visibility:"INTERNAL",url:""});async function submit(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/admin/documents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json();setMessage(r.ok?"Dokumen disimpan.":j.error);if(r.ok){setForm({...form,title:"",url:""});await reload()}}
  return <section className="ws-panel"><div className="ws-heading"><div><span>DOCUMENT CONTROL</span><h3>Dokumen UPPS dan program studi</h3></div><small>Visibilitas PUBLIK menentukan apakah metadata dokumen muncul pada website jurusan.</small></div><form className="doc-form" onSubmit={submit}><input placeholder="Judul dokumen" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>RENSTRA</option><option>VMTS</option><option>KURIKULUM</option><option>PEDOMAN</option><option>AKREDITASI</option></select><select value={form.unitId} disabled={user.role==="KAPRODI"} onChange={e=>setForm({...form,unitId:e.target.value})}><option>UPPS</option><option>NAUTIKA</option><option>KPN</option></select><select value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value})}><option>INTERNAL</option><option>PUBLIK</option></select><input placeholder="URL dokumen" value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/><button>Simpan</button></form><div className="doc-work-list">{docs.map(d=><div key={d.id}><b>{d.title}</b><span>{d.unitId} · {d.type} · {d.year}</span><em>{d.visibility}</em></div>)}</div></section>;
}

function UsersPanel({setMessage}:{setMessage:(s:string)=>void}){
  const [users,setUsers]=useState<Array<{id:number;email:string;name:string;role:string;unitId:string;active:number}>>([]),[form,setForm]=useState({email:"",name:"",role:"KAPRODI",unitId:"NAUTIKA",password:""});const load=useCallback(async()=>{const r=await fetch("/api/admin/users");if(r.ok)setUsers((await r.json()).users)},[]);useEffect(()=>{void load()},[load]);async function submit(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json();setMessage(r.ok?"Akun disimpan dan credential diperbarui bila password diisi.":j.error);if(r.ok){setForm({...form,email:"",name:"",password:""});await load()}}
  return <section className="ws-panel"><div className="ws-heading"><div><span>ADMINISTRASI SISTEM</span><h3>User, role, unit, credential</h3></div><small>Password minimal 10 karakter dan tidak pernah ditanam sebagai default bersama di source code.</small></div><form className="user-form" onSubmit={submit}><input type="email" placeholder="Email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="Nama" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{["ADMIN","KAJUR","SEKJUR","KAPRODI","GKM","VIEWER"].map(x=><option key={x}>{x}</option>)}</select><select value={form.unitId} onChange={e=>setForm({...form,unitId:e.target.value})}><option>UPPS</option><option>NAUTIKA</option><option>KPN</option><option>LAB</option></select><input type="password" minLength={10} placeholder="Password baru (opsional)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button>Simpan akun</button></form><div className="user-list">{users.map(u=><div key={u.id}><b>{u.name}</b><span>{u.email}</span><em>{u.role} · {u.unitId}</em></div>)}</div></section>;
}
